"""
Pact Provider Verification
───────────────────────────
Verifies the provider service against the consumer-generated Pact contracts.

The test starts the FastAPI provider in a background thread, runs Pact's
verification tool against it, and reports pass / fail per interaction.

Run:
    pytest tests/contract/test_provider_verification.py -v
"""

import os
import multiprocessing
import time

import pytest
import uvicorn
from pact import Verifier

from services.provider.app import app, store

# ── Configuration ────────────────────────────────────────────────────────────

PROVIDER_HOST = "127.0.0.1"
PROVIDER_PORT = 8999
PROVIDER_URL = f"http://{PROVIDER_HOST}:{PROVIDER_PORT}"
PACT_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "pacts")
PACT_FILE = os.path.join(
    PACT_DIR,
    "hrdashboardconsumer-employeemanagementprovider.json",
)


def _run_provider():
    """Start the provider in a subprocess."""
    uvicorn.run(app, host=PROVIDER_HOST, port=PROVIDER_PORT, log_level="warning")


@pytest.fixture(scope="module", autouse=True)
def provider_server():
    """Launch the real provider for Pact verification."""
    proc = multiprocessing.Process(target=_run_provider, daemon=True)
    proc.start()
    # Wait for the server to be ready
    import requests
    for _ in range(30):
        try:
            requests.get(f"{PROVIDER_URL}/health", timeout=1)
            break
        except Exception:
            time.sleep(0.5)
    yield
    proc.terminate()
    proc.join(timeout=5)


@pytest.fixture(autouse=True)
def reset_store():
    """Reset seed data between tests for provider state reproducibility."""
    store.reset()


class TestProviderVerification:
    """
    Verify that the provider satisfies every interaction defined in the
    Pact contract generated by the consumer.
    """

    def test_provider_honors_consumer_contract(self):
        verifier = Verifier(
            provider="EmployeeManagementProvider",
            provider_base_url=PROVIDER_URL,
        )

        output, logs = verifier.verify_pacts(
            PACT_FILE,
            provider_states_setup_url=f"{PROVIDER_URL}/_pact/provider-states",
            headers=["X-API-Key: contract-testing-key-2024"],
            verbose=True,
            enable_pending=False,
        )

        assert output == 0, f"Provider verification failed:\n{logs}"
